<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "student.dtd">-->

<!DOCTYPE students [
		<!ELEMENT students (student+) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		]>

<students>
	<student number="s001">
		<name></name>
		<age></age>
		<sex></sex>
	</student>
	<student number="s002">
		<name></name>
		<age></age>
		<sex></sex>
	</student>
</students>